[build]
  cli = "npm"
  command = "npm run build"
  publish = "dist/developer-portfolio"  # 👈 Replace with your actual project folder name in "dist/"
  node_version = "18.20.7"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
