[build]
  publish = "dist/developer-portfolio/browser"
  command = "yarn build:netlify"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "1.22.19"
  YARN_FLAGS = "--frozen-lockfile --prefer-offline"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "max-age=31536000"