
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ── ❶ Ensure the runner uses Node 18.20.7 ────────────────────────────────
      - name: Setup Node.js from .nvmrc
        uses: actions/setup-node@v3
        with:
          # will read the Node version from your .nvmrc file
          node-version-file: '.nvmrc'
          cache: 'npm'

      # ── ❷ Install dependencies ────────────────────────────────────────────────
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
